package com.shim.secretdoors.datagen;

import com.shim.secretdoors.SecretDoors;
import com.shim.secretdoors.registry.SDBlocks;
import com.shim.secretdoors.registry.SDTags;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BlockTagsProvider;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.data.ExistingFileHelper;

public class ModBlockTags extends BlockTagsProvider {

    public ModBlockTags(DataGenerator generator, ExistingFileHelper helper) {
        super(generator, SecretDoors.MODID, helper);
    }

    @Override
    protected void addTags() {

        //---- DOORS -------------------------------------------------------------------------------
        tag(SDTags.Blocks.SECRET_BOOKSHELF_DOORS)
                .add(SDBlocks.SECRET_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_ASPEN_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_BAOBAB_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_ENCHANTED_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_CHERRY_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_CIKA_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_CYPRESS_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_EBONY_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_FIR_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_GREEN_ENCHANTED_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_HOLLY_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_JACARANDA_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_MAHOGANY_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_MANGROVE_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_MAPLE_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_PINE_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_RAINBOW_EUCALYPTUS_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_REDWOOD_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_SKYRIS_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_WILLOW_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_WITCH_HAZEL_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_ZELKOVA_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_SYTHIAN_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_EMBUR_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_PALM_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_LAMENT_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_BULBIS_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_NIGHTSHADE_BOOKSHELF_DOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_BOOKSHELF_DOOR.get()).add(SDBlocks.SECRET_BYG_IMPARIUS_BOOKSHELF_DOOR.get());

        tag(SDTags.Blocks.SECRET_WOODEN_PLANK_DOORS)
                .add(SDBlocks.SECRET_OAK_PLANK_DOOR.get()).add(SDBlocks.SECRET_DARK_OAK_PLANK_DOOR.get()).add(SDBlocks.SECRET_BIRCH_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_ACACIA_PLANK_DOOR.get()).add(SDBlocks.SECRET_SPRUCE_PLANK_DOOR.get()).add(SDBlocks.SECRET_JUNGLE_PLANK_DOOR.get())

                .add(SDBlocks.SECRET_BOP_FIR_PLANK_DOOR.get()).add(SDBlocks.SECRET_BOP_REDWOOD_PLANK_DOOR.get()).add(SDBlocks.SECRET_BOP_CHERRY_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BOP_MAHOGANY_PLANK_DOOR.get()).add(SDBlocks.SECRET_BOP_JACARANDA_PLANK_DOOR.get()).add(SDBlocks.SECRET_BOP_PALM_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BOP_WILLOW_PLANK_DOOR.get()).add(SDBlocks.SECRET_BOP_DEAD_PLANK_DOOR.get()).add(SDBlocks.SECRET_BOP_MAGIC_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BOP_UMBRAN_PLANK_DOOR.get()).add(SDBlocks.SECRET_BOP_HELLBARK_PLANK_DOOR.get())

                .add(SDBlocks.SECRET_BYG_ASPEN_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_BAOBAB_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_ENCHANTED_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_CHERRY_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_CIKA_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_CYPRESS_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_EBONY_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_FIR_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_GREEN_ENCHANTED_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_HOLLY_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_JACARANDA_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_MAHOGANY_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_MANGROVE_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_MAPLE_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_PINE_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_RAINBOW_EUCALYPTUS_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_REDWOOD_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_SKYRIS_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_WILLOW_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_WITCH_HAZEL_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_ZELKOVA_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_SYTHIAN_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_EMBUR_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_PALM_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_LAMENT_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_BULBIS_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_NIGHTSHADE_PLANK_DOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_PLANK_DOOR.get()).add(SDBlocks.SECRET_BYG_IMPARIUS_PLANK_DOOR.get());

        tag(SDTags.Blocks.SECRET_LOG_DOORS)
                .add(SDBlocks.SECRET_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_DARK_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_BIRCH_LOG_DOOR.get())
                .add(SDBlocks.SECRET_ACACIA_LOG_DOOR.get()).add(SDBlocks.SECRET_SPRUCE_LOG_DOOR.get()).add(SDBlocks.SECRET_JUNGLE_LOG_DOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_DARK_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BIRCH_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_ACACIA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_SPRUCE_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_JUNGLE_LOG_DOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_DARK_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BIRCH_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_ACACIA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_SPRUCE_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_JUNGLE_LOG_DOOR.get())

                .add(SDBlocks.SECRET_HORIZONTAL_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_DARK_OAK_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BIRCH_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_ACACIA_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_SPRUCE_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_JUNGLE_LOG_DOOR.get())

                .add(SDBlocks.SECRET_BOP_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_BOP_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_BOP_CHERRY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BOP_MAHOGANY_LOG_DOOR.get()).add(SDBlocks.SECRET_BOP_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_BOP_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BOP_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_BOP_DEAD_LOG_DOOR.get()).add(SDBlocks.SECRET_BOP_MAGIC_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BOP_UMBRAN_LOG_DOOR.get()).add(SDBlocks.SECRET_BOP_HELLBARK_LOG_DOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_BOP_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_CHERRY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BOP_MAHOGANY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BOP_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_DEAD_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_MAGIC_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BOP_UMBRAN_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_HELLBARK_LOG_DOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_CHERRY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_MAHOGANY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_DEAD_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_MAGIC_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_UMBRAN_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BOP_HELLBARK_LOG_DOOR.get())

                .add(SDBlocks.SECRET_HORIZONTAL_BOP_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BOP_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BOP_CHERRY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BOP_MAHOGANY_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BOP_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BOP_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BOP_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BOP_DEAD_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BOP_MAGIC_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BOP_UMBRAN_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BOP_HELLBARK_LOG_DOOR.get())

                .add(SDBlocks.SECRET_BYG_ASPEN_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_BAOBAB_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_CHERRY_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_CIKA_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_CYPRESS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_EBONY_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_GREEN_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_HOLLY_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_MAHOGANY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_MANGROVE_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_MAPLE_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_PINE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_RAINBOW_EUCALYPTUS_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_SKYRIS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_WITCH_HAZEL_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_ZELKOVA_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_SYTHIAN_STEM_DOOR.get()).add(SDBlocks.SECRET_BYG_EMBUR_PEDU_DOOR.get()).add(SDBlocks.SECRET_BYG_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_LAMENT_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_BULBIS_STEM_DOOR.get()).add(SDBlocks.SECRET_BYG_NIGHTSHADE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_LOG_DOOR.get()).add(SDBlocks.SECRET_BYG_IMPARIUS_STEM_DOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_BYG_ASPEN_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_BAOBAB_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_BLUE_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_CHERRY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_CIKA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_CYPRESS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_EBONY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_GREEN_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_HOLLY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_MAHOGANY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_MANGROVE_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_MAPLE_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_PINE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_RAINBOW_EUCALYPTUS_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_SKYRIS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_WITCH_HAZEL_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_ZELKOVA_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_SYTHIAN_STEM_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_EMBUR_PEDU_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_LAMENT_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_BULBIS_STEM_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_NIGHTSHADE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_ETHER_LOG_DOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_ASPEN_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_BAOBAB_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_BLUE_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_CHERRY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_CIKA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_CYPRESS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_EBONY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_GREEN_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_HOLLY_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_MAHOGANY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_MANGROVE_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_MAPLE_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_PINE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_RAINBOW_EUCALYPTUS_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_SKYRIS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_WITCH_HAZEL_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_ZELKOVA_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_SYTHIAN_STEM_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_EMBUR_PEDU_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_LAMENT_LOG_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_BULBIS_STEM_DOOR.get()).add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_NIGHTSHADE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_HORIZONTAL_BYG_ETHER_LOG_DOOR.get())

                .add(SDBlocks.SECRET_HORIZONTAL_BYG_ASPEN_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_BAOBAB_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_BLUE_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_CHERRY_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_CIKA_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_CYPRESS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_EBONY_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_FIR_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_GREEN_ENCHANTED_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_HOLLY_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_JACARANDA_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_MAHOGANY_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_MANGROVE_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_MAPLE_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_PINE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_RAINBOW_EUCALYPTUS_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_REDWOOD_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_SKYRIS_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_WILLOW_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_WITCH_HAZEL_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_ZELKOVA_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_SYTHIAN_STEM_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_EMBUR_PEDU_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_PALM_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_LAMENT_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_BULBIS_STEM_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_NIGHTSHADE_LOG_DOOR.get())
                .add(SDBlocks.SECRET_HORIZONTAL_BYG_ETHER_LOG_DOOR.get()).add(SDBlocks.SECRET_HORIZONTAL_BYG_IMPARIUS_STEM_DOOR.get());

        tag(SDTags.Blocks.SECRET_STONE_DOORS)
                .add(SDBlocks.SECRET_STONE_DOOR.get()).add(SDBlocks.SECRET_COBBLESTONE_DOOR.get()).add(SDBlocks.SECRET_STONE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_COBBLED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_DEEPSLATE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_POLISHED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_DEEPSLATE_TILES_DOOR.get())

                .add(SDBlocks.SECRET_NETHERRACK_DOOR.get()).add(SDBlocks.SECRET_NETHER_BRICK_DOOR.get()).add(SDBlocks.SECRET_POLISHED_BLACKSTONE_DOOR.get())
                .add(SDBlocks.SECRET_POLISHED_BASALT_DOOR.get()).add(SDBlocks.SECRET_BLACKSTONE_DOOR.get()).add(SDBlocks.SECRET_ANDESITE_DOOR.get())
                .add(SDBlocks.SECRET_POLISHED_ANDESITE_DOOR.get()).add(SDBlocks.SECRET_DIORITE_DOOR.get()).add(SDBlocks.SECRET_POLISHED_DIORITE_DOOR.get())
                .add(SDBlocks.SECRET_GRANITE_DOOR.get()).add(SDBlocks.SECRET_POLISHED_GRANITE_DOOR.get())

                .add(SDBlocks.SECRET_QUARTZ_BLOCK_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_QUARTZ_DOOR.get()).add(SDBlocks.SECRET_QUARTZ_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_RED_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_RED_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_RED_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BRICKS_DOOR.get()).add(SDBlocks.SECRET_PURPUR_DOOR.get()).add(SDBlocks.SECRET_END_STONE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_PRISMARINE_BRICKS_DOOR.get()).add(SDBlocks.SECRET_DARK_PRISMARINE_DOOR.get())

                .add(SDBlocks.SECRET_MOON_STONE_DOOR.get()).add(SDBlocks.SECRET_MOON_COBBLESTONE_DOOR.get()).add(SDBlocks.SECRET_MOON_STONE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_MOON_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MOON_COBBLED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MOON_DEEPSLATE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_MOON_POLISHED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MOON_DEEPSLATE_TILES_DOOR.get())

                .add(SDBlocks.SECRET_MARS_STONE_DOOR.get()).add(SDBlocks.SECRET_MARS_COBBLESTONE_DOOR.get()).add(SDBlocks.SECRET_MARS_STONE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_MARS_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MARS_COBBLED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MARS_DEEPSLATE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_MARS_POLISHED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MARS_DEEPSLATE_TILES_DOOR.get())

                .add(SDBlocks.SECRET_VENUS_STONE_DOOR.get()).add(SDBlocks.SECRET_VENUS_COBBLESTONE_DOOR.get()).add(SDBlocks.SECRET_VENUS_STONE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_VENUS_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_VENUS_COBBLED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_VENUS_DEEPSLATE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_VENUS_POLISHED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_VENUS_DEEPSLATE_TILES_DOOR.get())

                .add(SDBlocks.SECRET_MERCURY_STONE_DOOR.get()).add(SDBlocks.SECRET_MERCURY_COBBLESTONE_DOOR.get()).add(SDBlocks.SECRET_MERCURY_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_MERCURY_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MERCURY_COBBLED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_MERCURY_DEEPSLATE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_MERCURY_DEEPSLATE_TILES_DOOR.get()).add(SDBlocks.SECRET_MERCURY_POLISHED_DEEPSLATE_DOOR.get())

                .add(SDBlocks.SECRET_JUPITER_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_JUPITER_COBBLED_DEEPSLATE_DOOR.get()).add(SDBlocks.SECRET_JUPITER_DEEPSLATE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_JUPITER_DEEPSLATE_TILES_DOOR.get()).add(SDBlocks.SECRET_JUPITER_POLISHED_DEEPSLATE_DOOR.get())

                .add(SDBlocks.SECRET_EUROPA_BRICKS_DOOR.get()).add(SDBlocks.SECRET_CALLISTO_BRICKS_DOOR.get())

                .add(SDBlocks.SECRET_PANEL_DOOR.get())

                .add(SDBlocks.SECRET_METEOR_DOOR.get()).add(SDBlocks.SECRET_METEOR_BRICKS_DOOR.get())

                .add(SDBlocks.SECRET_BOP_WHITE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BOP_WHITE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BOP_WHITE_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BOP_ORANGE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BOP_ORANGE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BOP_ORANGE_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BOP_BLACK_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BOP_BLACK_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BOP_BLACK_SANDSTONE_DOOR.get())

                .add(SDBlocks.SECRET_BOP_MUD_BRICKS_DOOR.get())

                .add(SDBlocks.SECRET_BYG_WHITE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BYG_WHITE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_WHITE_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_BLUE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BYG_BLUE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_BLUE_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_BLACK_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BYG_BLACK_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_BLACK_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_PURPLE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BYG_PURPLE_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_PURPLE_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_PINK_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BYG_PINK_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_PINK_SANDSTONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_WINDSWEPT_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_CUT_BYG_WINDSWEPT_SANDSTONE_DOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_WINDSWEPT_SANDSTONE_DOOR.get())

                .add(SDBlocks.SECRET_BYG_MUD_BRICKS_DOOR.get()).add(SDBlocks.SECRET_BYG_BRIMSTONE_DOOR.get()).add(SDBlocks.SECRET_BYG_PURPUR_STONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_STONE_DOOR.get()).add(SDBlocks.SECRET_BYG_COBBLED_ETHER_DOOR.get())
                .add(SDBlocks.SECRET_BYG_DACITE_DOOR.get()).add(SDBlocks.SECRET_BYG_DACITE_BRICKS_DOOR.get()).add(SDBlocks.SECRET_BYG_DACITE_COBBLESTONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_DACITE_TILES_DOOR.get())
                .add(SDBlocks.SECRET_BYG_RED_ROCK_DOOR.get()).add(SDBlocks.SECRET_BYG_RED_ROCK_BRICKS_DOOR.get()).add(SDBlocks.SECRET_BYG_ROCKY_STONE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_TRAVERTINE_DOOR.get()).add(SDBlocks.SECRET_BYG_POLISHED_TRAVERTINE_DOOR.get())
                .add(SDBlocks.SECRET_BYG_SCORIA_STONE_DOOR.get()).add(SDBlocks.SECRET_BYG_SCORIA_COBBLESTONE_DOOR.get()).add(SDBlocks.SECRET_BYG_SCORIA_STONE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_BYG_SOAPSTONE_DOOR.get()).add(SDBlocks.SECRET_BYG_POLISHED_SOAPSTONE_DOOR.get()).add(SDBlocks.SECRET_BYG_SOAPSTONE_BRICKS_DOOR.get())
                .add(SDBlocks.SECRET_BYG_SOAPSTONE_TILES_DOOR.get())
                .add(SDBlocks.SECRET_BYG_MAGMATIC_STONE_DOOR.get()).add(SDBlocks.SECRET_BYG_THERIUM_DOOR.get()).add(SDBlocks.SECRET_BYG_CRYPTIC_STONE_DOOR.get());

        tag(SDTags.Blocks.SECRET_WOODEN_DOORS)
                .addTag(SDTags.Blocks.SECRET_WOODEN_PLANK_DOORS)
                .addTag(SDTags.Blocks.SECRET_LOG_DOORS)
                .addTag(SDTags.Blocks.SECRET_BOOKSHELF_DOORS);

        tag(BlockTags.WOODEN_DOORS)
                .addTag(SDTags.Blocks.SECRET_WOODEN_DOORS);

        tag(BlockTags.DOORS)
                .addTag(SDTags.Blocks.SECRET_WOODEN_DOORS)
                .addTag(SDTags.Blocks.SECRET_STONE_DOORS)

                .add(SDBlocks.SECRET_BLACK_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_GREY_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_LIGHT_GREY_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_WHITE_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_PURPLE_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_BLUE_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_LIGHT_BLUE_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_CYAN_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_GREEN_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_LIME_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_YELLOW_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_ORANGE_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_RED_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_BROWN_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_PINK_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MAGENTA_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_CERAMIC_TRAPDOOR.get())

                .add(SDBlocks.SECRET_NETHERRACK_DOOR.get()).add(SDBlocks.SECRET_NETHER_BRICK_DOOR.get())

                .add(SDBlocks.SECRET_BYG_BLUE_NETHERRACK_DOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_NETHER_BRICK_DOOR.get()).add(SDBlocks.SECRET_BYG_YELLOW_NETHER_BRICK_DOOR.get());


        //---- TRAPDOORS -------------------------------------------------------------------------------
        tag(SDTags.Blocks.SECRET_BOOKSHELF_TRAPDOORS)
                .add(SDBlocks.SECRET_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_ASPEN_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BAOBAB_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_ENCHANTED_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_CHERRY_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_CIKA_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_CYPRESS_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_EBONY_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_FIR_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_GREEN_ENCHANTED_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_HOLLY_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_JACARANDA_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_MAHOGANY_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_MANGROVE_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_MAPLE_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_PINE_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_RAINBOW_EUCALYPTUS_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_REDWOOD_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_SKYRIS_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_WILLOW_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_WITCH_HAZEL_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_ZELKOVA_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_SYTHIAN_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_EMBUR_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_PALM_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_LAMENT_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BULBIS_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_NIGHTSHADE_BOOKSHELF_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_BOOKSHELF_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_IMPARIUS_BOOKSHELF_TRAPDOOR.get());

        tag(SDTags.Blocks.SECRET_WOODEN_PLANK_TRAPDOORS)
                .add(SDBlocks.SECRET_OAK_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_DARK_OAK_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BIRCH_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_ACACIA_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_SPRUCE_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_JUNGLE_PLANK_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BOP_FIR_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_REDWOOD_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_CHERRY_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_MAHOGANY_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_JACARANDA_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_PALM_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_WILLOW_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_DEAD_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_MAGIC_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_UMBRAN_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_HELLBARK_PLANK_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BYG_ASPEN_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BAOBAB_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_ENCHANTED_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_CHERRY_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_CIKA_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_CYPRESS_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_EBONY_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_FIR_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_GREEN_ENCHANTED_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_HOLLY_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_JACARANDA_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_MAHOGANY_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_MANGROVE_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_MAPLE_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_PINE_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_RAINBOW_EUCALYPTUS_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_REDWOOD_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_SKYRIS_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_WILLOW_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_WITCH_HAZEL_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_ZELKOVA_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_SYTHIAN_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_EMBUR_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_PALM_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_LAMENT_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BULBIS_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_NIGHTSHADE_PLANK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_PLANK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_IMPARIUS_PLANK_TRAPDOOR.get());

        tag(SDTags.Blocks.SECRET_LOG_TRAPDOORS)
                .add(SDBlocks.SECRET_OAK_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_DARK_OAK_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BIRCH_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_ACACIA_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_SPRUCE_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_JUNGLE_LOG_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BOP_FIR_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_REDWOOD_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_CHERRY_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_MAHOGANY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_JACARANDA_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_PALM_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_WILLOW_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_DEAD_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_MAGIC_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_UMBRAN_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BOP_HELLBARK_LOG_TRAPDOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_BOP_FIR_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_REDWOOD_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_CHERRY_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BOP_MAHOGANY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_JACARANDA_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_PALM_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BOP_WILLOW_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_DEAD_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_MAGIC_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BOP_UMBRAN_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BOP_HELLBARK_LOG_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BYG_ASPEN_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BAOBAB_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_ENCHANTED_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_CHERRY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_CIKA_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_CYPRESS_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_EBONY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_FIR_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_GREEN_ENCHANTED_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_HOLLY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_JACARANDA_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_MAHOGANY_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_MANGROVE_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_MAPLE_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_PINE_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_RAINBOW_EUCALYPTUS_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_REDWOOD_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_SKYRIS_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_WILLOW_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_WITCH_HAZEL_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_ZELKOVA_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_SYTHIAN_STEM_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_EMBUR_PEDU_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_PALM_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_LAMENT_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BULBIS_STEM_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_NIGHTSHADE_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_IMPARIUS_STEM_TRAPDOOR.get())

                .add(SDBlocks.SECRET_STRIPPED_BYG_ASPEN_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_BAOBAB_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_BLUE_ENCHANTED_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_CHERRY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_CIKA_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_CYPRESS_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_EBONY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_FIR_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_GREEN_ENCHANTED_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_HOLLY_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_JACARANDA_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_MAHOGANY_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_MANGROVE_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_MAPLE_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_PINE_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_RAINBOW_EUCALYPTUS_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_REDWOOD_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_SKYRIS_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_WILLOW_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_WITCH_HAZEL_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_ZELKOVA_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_SYTHIAN_STEM_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_EMBUR_PEDU_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_PALM_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_LAMENT_LOG_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_BULBIS_STEM_TRAPDOOR.get()).add(SDBlocks.SECRET_STRIPPED_BYG_NIGHTSHADE_LOG_TRAPDOOR.get())
                .add(SDBlocks.SECRET_STRIPPED_BYG_ETHER_LOG_TRAPDOOR.get());

        tag(SDTags.Blocks.SECRET_STONE_TRAPDOORS)
                .add(SDBlocks.SECRET_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_COBBLESTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_STONE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_COBBLED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_DEEPSLATE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_POLISHED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_DEEPSLATE_TILES_TRAPDOOR.get())

                .add(SDBlocks.SECRET_NETHERRACK_TRAPDOOR.get()).add(SDBlocks.SECRET_NETHER_BRICK_TRAPDOOR.get()).add(SDBlocks.SECRET_POLISHED_BLACKSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_POLISHED_BASALT_TRAPDOOR.get()).add(SDBlocks.SECRET_BLACKSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_ANDESITE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_POLISHED_ANDESITE_TRAPDOOR.get()).add(SDBlocks.SECRET_DIORITE_TRAPDOOR.get()).add(SDBlocks.SECRET_POLISHED_DIORITE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_GRANITE_TRAPDOOR.get()).add(SDBlocks.SECRET_POLISHED_GRANITE_TRAPDOOR.get())

                .add(SDBlocks.SECRET_QUARTZ_BLOCK_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_QUARTZ_TRAPDOOR.get()).add(SDBlocks.SECRET_QUARTZ_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_RED_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_RED_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_RED_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BRICKS_TRAPDOOR.get()).add(SDBlocks.SECRET_PURPUR_TRAPDOOR.get()).add(SDBlocks.SECRET_END_STONE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_PRISMARINE_BRICKS_TRAPDOOR.get()).add(SDBlocks.SECRET_DARK_PRISMARINE_TRAPDOOR.get())

                .add(SDBlocks.SECRET_MOON_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_MOON_COBBLESTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_MOON_STONE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MOON_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MOON_COBBLED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MOON_DEEPSLATE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MOON_POLISHED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MOON_DEEPSLATE_TILES_TRAPDOOR.get())

                .add(SDBlocks.SECRET_MARS_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_MARS_COBBLESTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_MARS_STONE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MARS_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MARS_COBBLED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MARS_DEEPSLATE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MARS_POLISHED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MARS_DEEPSLATE_TILES_TRAPDOOR.get())

                .add(SDBlocks.SECRET_VENUS_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_VENUS_COBBLESTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_VENUS_STONE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_VENUS_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_VENUS_COBBLED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_VENUS_DEEPSLATE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_VENUS_POLISHED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_VENUS_DEEPSLATE_TILES_TRAPDOOR.get())

                .add(SDBlocks.SECRET_MERCURY_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_MERCURY_COBBLESTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_MERCURY_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MERCURY_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MERCURY_COBBLED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_MERCURY_DEEPSLATE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MERCURY_DEEPSLATE_TILES_TRAPDOOR.get()).add(SDBlocks.SECRET_MERCURY_POLISHED_DEEPSLATE_TRAPDOOR.get())

                .add(SDBlocks.SECRET_JUPITER_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_JUPITER_COBBLED_DEEPSLATE_TRAPDOOR.get()).add(SDBlocks.SECRET_JUPITER_DEEPSLATE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_JUPITER_DEEPSLATE_TILES_TRAPDOOR.get()).add(SDBlocks.SECRET_JUPITER_POLISHED_DEEPSLATE_TRAPDOOR.get())

                .add(SDBlocks.SECRET_EUROPA_BRICKS_TRAPDOOR.get()).add(SDBlocks.SECRET_CALLISTO_BRICKS_TRAPDOOR.get())

                .add(SDBlocks.SECRET_PANEL_TRAPDOOR.get())

                .add(SDBlocks.SECRET_METEOR_TRAPDOOR.get()).add(SDBlocks.SECRET_METEOR_BRICKS_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BOP_WHITE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BOP_WHITE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BOP_WHITE_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_ORANGE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BOP_ORANGE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BOP_ORANGE_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BOP_BLACK_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BOP_BLACK_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BOP_BLACK_SANDSTONE_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BOP_MUD_BRICKS_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BYG_WHITE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BYG_WHITE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_WHITE_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_BLUE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BYG_BLUE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_BLUE_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_BLACK_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BYG_BLACK_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_BLACK_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_PURPLE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BYG_PURPLE_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_PURPLE_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_PINK_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BYG_PINK_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_PINK_SANDSTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_WINDSWEPT_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_CUT_BYG_WINDSWEPT_SANDSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_SMOOTH_BYG_WINDSWEPT_SANDSTONE_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BYG_MUD_BRICKS_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BRIMSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_PURPUR_STONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_ETHER_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_COBBLED_ETHER_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_DACITE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_DACITE_BRICKS_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_DACITE_COBBLESTONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_DACITE_TILES_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_RED_ROCK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_RED_ROCK_BRICKS_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_ROCKY_STONE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_TRAVERTINE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_POLISHED_TRAVERTINE_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_SCORIA_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_SCORIA_COBBLESTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_SCORIA_STONE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_SOAPSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_POLISHED_SOAPSTONE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_SOAPSTONE_BRICKS_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_SOAPSTONE_TILES_TRAPDOOR.get())
                .add(SDBlocks.SECRET_BYG_MAGMATIC_STONE_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_THERIUM_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_CRYPTIC_STONE_TRAPDOOR.get());

        tag(SDTags.Blocks.SECRET_WOODEN_TRAPDOORS)
                .addTag(SDTags.Blocks.SECRET_WOODEN_PLANK_TRAPDOORS)
                .addTag(SDTags.Blocks.SECRET_LOG_TRAPDOORS)
                .addTag(SDTags.Blocks.SECRET_BOOKSHELF_TRAPDOORS);

        tag(BlockTags.WOODEN_TRAPDOORS)
                .addTag(SDTags.Blocks.SECRET_WOODEN_TRAPDOORS);

        tag(BlockTags.TRAPDOORS)
                .addTag(SDTags.Blocks.SECRET_WOODEN_TRAPDOORS)
                .addTag(SDTags.Blocks.SECRET_STONE_TRAPDOORS)

                .add(SDBlocks.SECRET_BLACK_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_GREY_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_LIGHT_GREY_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_WHITE_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_PURPLE_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_BLUE_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_LIGHT_BLUE_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_CYAN_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_GREEN_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_LIME_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_YELLOW_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_ORANGE_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_RED_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_BROWN_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_PINK_CERAMIC_TRAPDOOR.get())
                .add(SDBlocks.SECRET_MAGENTA_CERAMIC_TRAPDOOR.get()).add(SDBlocks.SECRET_CERAMIC_TRAPDOOR.get())

                .add(SDBlocks.SECRET_NETHERRACK_TRAPDOOR.get())
                .add(SDBlocks.SECRET_NETHER_BRICK_TRAPDOOR.get())

                .add(SDBlocks.SECRET_BYG_BLUE_NETHERRACK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_BLUE_NETHER_BRICK_TRAPDOOR.get()).add(SDBlocks.SECRET_BYG_YELLOW_NETHER_BRICK_TRAPDOOR.get());
    }
}
