package com.shim.secretdoors.registry;

import com.shim.secretdoors.SecretDoors;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.material.Material;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.function.Supplier;

public class SDBlocks {

    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, SecretDoors.MODID);
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, SecretDoors.MODID);

    public static final Map<RegistryObject<? extends Block>, String> BLOCK_LANG_EN_US = new HashMap<>();
    public static final LinkedList<RegistryObject<? extends Block>> DOOR_LOOT_TABLE = new LinkedList<>();
    public static final LinkedList<RegistryObject<? extends Block>> TRAPDOOR_LOOT_TABLE = new LinkedList<>();

    private static <T extends Block> RegistryObject<T> registerDoorBlock(String nameIn, String localizationIn, Supplier<T> blockIn) {
        RegistryObject<T> block = BLOCKS.register(nameIn, blockIn);
        ITEMS.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(CreativeModeTab.TAB_DECORATIONS)));
        BLOCK_LANG_EN_US.put(block, localizationIn);
        DOOR_LOOT_TABLE.add(block);
        return block;
    }

    private static <T extends Block> RegistryObject<T> registerTrapdoorBlock(String nameIn, String localizationIn, Supplier<T> blockIn) {
        RegistryObject<T> block = BLOCKS.register(nameIn, blockIn);
        ITEMS.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(CreativeModeTab.TAB_DECORATIONS)));
        BLOCK_LANG_EN_US.put(block, localizationIn);
        TRAPDOOR_LOOT_TABLE.add(block);
        return block;
    }

    public static final RegistryObject<DoorBlock> SECRET_OAK_PLANK_DOOR = registerDoorBlock("secret_oak_plank_door", "Secret Oak Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_DARK_OAK_PLANK_DOOR = registerDoorBlock("secret_dark_oak_plank_door", "Secret Dark Oak Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_SPRUCE_PLANK_DOOR = registerDoorBlock("secret_spruce_plank_door", "Secret Spruce Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_ACACIA_PLANK_DOOR = registerDoorBlock("secret_acacia_plank_door", "Secret Acacia Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_BIRCH_PLANK_DOOR = registerDoorBlock("secret_birch_plank_door", "Secret Birch Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_JUNGLE_PLANK_DOOR = registerDoorBlock("secret_jungle_plank_door", "Secret Jungle Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_CRIMSON_PLANK_DOOR = registerDoorBlock("secret_crimson_plank_door", "Secret Crimson Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.CRIMSON_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_WARPED_PLANK_DOOR = registerDoorBlock("secret_warped_plank_door", "Secret Warped Plank Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.WARPED_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_OAK_LOG_DOOR = registerDoorBlock("secret_oak_log_door", "Secret Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_DARK_OAK_LOG_DOOR = registerDoorBlock("secret_dark_oak_log_door", "Secret Dark Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_SPRUCE_LOG_DOOR = registerDoorBlock("secret_spruce_log_door", "Secret Spruce Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_ACACIA_LOG_DOOR = registerDoorBlock("secret_acacia_log_door", "Secret Acacia Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_BIRCH_LOG_DOOR = registerDoorBlock("secret_birch_log_door", "Secret Birch Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_JUNGLE_LOG_DOOR = registerDoorBlock("secret_jungle_log_door", "Secret Jungle Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_CRIMSON_STEM_DOOR = registerDoorBlock("secret_crimson_stem_door", "Secret Crimson Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.CRIMSON_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_WARPED_STEM_DOOR = registerDoorBlock("secret_warped_stem_door", "Secret Warped Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.WARPED_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_OAK_LOG_DOOR = registerDoorBlock("secret_stripped_oak_log_door", "Secret Stripped Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_DARK_OAK_LOG_DOOR = registerDoorBlock("secret_stripped_dark_oak_log_door", "Secret Stripped Dark Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_SPRUCE_LOG_DOOR = registerDoorBlock("secret_stripped_spruce_log_door", "Secret Stripped Spruce Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_ACACIA_LOG_DOOR = registerDoorBlock("secret_stripped_acacia_log_door", "Secret Stripped Acacia Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_BIRCH_LOG_DOOR = registerDoorBlock("secret_stripped_birch_log_door", "Secret Stripped Birch Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_JUNGLE_LOG_DOOR = registerDoorBlock("secret_stripped_jungle_log_door", "Secret Stripped Jungle Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_CRIMSON_STEM_DOOR = registerDoorBlock("secret_stripped_crimson_stem_door", "Secret Stripped Crimson Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.STRIPPED_CRIMSON_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_WARPED_STEM_DOOR = registerDoorBlock("secret_stripped_warped_stem_door", "Secret Stripped Warped Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.STRIPPED_WARPED_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_OAK_LOG_DOOR = registerDoorBlock("secret_stripped_horizontal_oak_log_door", "Secret Stripped Horizontal Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_DARK_OAK_LOG_DOOR = registerDoorBlock("secret_stripped_horizontal_dark_oak_log_door", "Secret Stripped Horizontal Dark Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_SPRUCE_LOG_DOOR = registerDoorBlock("secret_stripped_horizontal_spruce_log_door", "Secret Stripped Horizontal Spruce Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_ACACIA_LOG_DOOR = registerDoorBlock("secret_stripped_horizontal_acacia_log_door", "Secret Stripped Horizontal Acacia Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_BIRCH_LOG_DOOR = registerDoorBlock("secret_stripped_horizontal_birch_log_door", "Secret Stripped Horizontal Birch Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_JUNGLE_LOG_DOOR = registerDoorBlock("secret_stripped_horizontal_jungle_log_door", "Secret Stripped Horizontal Jungle Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_CRIMSON_STEM_DOOR = registerDoorBlock("secret_stripped_horizontal_crimson_stem_door", "Secret Stripped Horizontal Crimson Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.STRIPPED_CRIMSON_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STRIPPED_HORIZONTAL_WARPED_STEM_DOOR = registerDoorBlock("secret_stripped_horizontal_warped_stem_door", "Secret Stripped Horizontal Warped Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.STRIPPED_WARPED_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_OAK_LOG_DOOR = registerDoorBlock("secret_horizontal_oak_log_door", "Secret Horizontal Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_DARK_OAK_LOG_DOOR = registerDoorBlock("secret_horizontal_dark_oak_log_door", "Secret Horizontal Dark Oak Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_SPRUCE_LOG_DOOR = registerDoorBlock("secret_horizontal_spruce_log_door", "Secret Horizontal Spruce Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_ACACIA_LOG_DOOR = registerDoorBlock("secret_horizontal_acacia_log_door", "Secret Horizontal Acacia Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_BIRCH_LOG_DOOR = registerDoorBlock("secret_horizontal_birch_log_door", "Secret Horizontal Birch Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_JUNGLE_LOG_DOOR = registerDoorBlock("secret_horizontal_jungle_log_door", "Secret Horizontal Jungle Log Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_CRIMSON_STEM_DOOR = registerDoorBlock("secret_horizontal_crimson_stem_door", "Secret Horizontal Crimson Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.CRIMSON_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_HORIZONTAL_WARPED_STEM_DOOR = registerDoorBlock("secret_horizontal_warped_stem_door", "Secret Horizontal Warped Stem Door", () -> new DoorBlock(Block.Properties.of(Material.WOOD, Blocks.WARPED_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_STONE_DOOR = registerDoorBlock("secret_stone_door", "Secret Stone Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.STONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_COBBLESTONE_DOOR = registerDoorBlock("secret_cobblestone_door", "Secret Cobblestone Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.COBBLESTONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_STONE_BRICKS_DOOR = registerDoorBlock("secret_stone_bricks_door", "Secret Stone Bricks Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.STONE_BRICKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_DEEPSLATE_DOOR = registerDoorBlock("secret_deepslate_door", "Secret Deepslate Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.DEEPSLATE.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_COBBLED_DEEPSLATE_DOOR = registerDoorBlock("secret_cobbled_deepslate_door", "Secret Cobbled Deepslate Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.COBBLED_DEEPSLATE.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_DEEPSLATE_BRICKS_DOOR = registerDoorBlock("secret_deepslate_bricks_door", "Secret Deepslate Bricks Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.DEEPSLATE_BRICKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE_BRICKS).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_DEEPSLATE_TILES_DOOR = registerDoorBlock("secret_deepslate_tiles_door", "Secret Deepslate Tiles Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.DEEPSLATE_TILES.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE_TILES).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_POLISHED_DEEPSLATE_DOOR = registerDoorBlock("secret_polished_deepslate_door", "Secret Polished Deepslate Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_DEEPSLATE.defaultMaterialColor()).strength(3.0F).sound(SoundType.POLISHED_DEEPSLATE).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_BOOKSHELF_DOOR = registerDoorBlock("secret_bookshelf_door", "Secret Bookshelf Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.BOOKSHELF.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_NETHERRACK_DOOR = registerDoorBlock("secret_netherrack_door", "Secret Netherrack Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.NETHERRACK.defaultMaterialColor()).strength(3.0F).sound(SoundType.NETHERRACK).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_NETHER_BRICK_DOOR = registerDoorBlock("secret_nether_brick_door", "Secret Nether Brick Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.NETHER_BRICKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.NETHER_BRICKS).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_POLISHED_BLACKSTONE_DOOR = registerDoorBlock("secret_polished_blackstone_door", "Secret Polished Blackstone Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_BLACKSTONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_POLISHED_BASALT_DOOR = registerDoorBlock("secret_polished_basalt_door", "Secret Polished Basalt Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_BASALT.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_BLACKSTONE_DOOR = registerDoorBlock("secret_blackstone_door", "Secret Blackstone Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.BLACKSTONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_ANDESITE_DOOR = registerDoorBlock("secret_andesite_door", "Secret Andesite Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.ANDESITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_POLISHED_ANDESITE_DOOR = registerDoorBlock("secret_polished_andesite_door", "Secret Polished Andesite Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_ANDESITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_DIORITE_DOOR = registerDoorBlock("secret_diorite_door", "Secret Diorite Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.DIORITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_POLISHED_DIORITE_DOOR = registerDoorBlock("secret_polished_diorite_door", "Secret Polished Diorite Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_DIORITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_GRANITE_DOOR = registerDoorBlock("secret_granite_door", "Secret Granite Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.GRANITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_POLISHED_GRANITE_DOOR = registerDoorBlock("secret_polished_granite_door", "Secret Polished Granite Door", () -> new DoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_GRANITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));

    public static final RegistryObject<DoorBlock> SECRET_QUARTZ_BLOCK_DOOR = registerDoorBlock("secret_quartz_block_door", "Secret Quartz Block Door", () -> new DoorBlock(Block.Properties.copy(Blocks.QUARTZ_BLOCK).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_SMOOTH_QUARTZ_DOOR = registerDoorBlock("secret_smooth_quartz_door", "Secret Smooth Quartz Door", () -> new DoorBlock(Block.Properties.copy(Blocks.SMOOTH_QUARTZ).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_QUARTZ_BRICKS_DOOR = registerDoorBlock("secret_quartz_bricks_door", "Secret Quartz Bricks Door", () -> new DoorBlock(Block.Properties.copy(Blocks.QUARTZ_BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_SANDSTONE_DOOR = registerDoorBlock("secret_sandstone_door", "Secret Sandstone Door", () -> new DoorBlock(Block.Properties.copy(Blocks.SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_CUT_SANDSTONE_DOOR = registerDoorBlock("secret_cut_sandstone_door", "Secret Cut Sandstone Door", () -> new DoorBlock(Block.Properties.copy(Blocks.CUT_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_SMOOTH_SANDSTONE_DOOR = registerDoorBlock("secret_smooth_sandstone_door", "Secret Smooth Sandstone Door", () -> new DoorBlock(Block.Properties.copy(Blocks.SMOOTH_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_RED_SANDSTONE_DOOR = registerDoorBlock("secret_red_sandstone_door", "Secret Red Sandstone Door", () -> new DoorBlock(Block.Properties.copy(Blocks.RED_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_CUT_RED_SANDSTONE_DOOR = registerDoorBlock("secret_cut_red_sandstone_door", "Secret Cut Red Sandstone Door", () -> new DoorBlock(Block.Properties.copy(Blocks.CUT_RED_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_SMOOTH_RED_SANDSTONE_DOOR = registerDoorBlock("secret_smooth_red_sandstone_door", "Secret Smooth Red Sandstone Door", () -> new DoorBlock(Block.Properties.copy(Blocks.SMOOTH_RED_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_BRICKS_DOOR = registerDoorBlock("secret_bricks_door", "Secret Bricks Door", () -> new DoorBlock(Block.Properties.copy(Blocks.BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_PURPUR_DOOR = registerDoorBlock("secret_purpur_door", "Secret Purpur Door", () -> new DoorBlock(Block.Properties.copy(Blocks.PURPUR_BLOCK).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_END_STONE_BRICKS_DOOR = registerDoorBlock("secret_end_stone_bricks_door", "Secret End Stone Bricks Door", () -> new DoorBlock(Block.Properties.copy(Blocks.END_STONE_BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_PRISMARINE_BRICKS_DOOR = registerDoorBlock("secret_prismarine_bricks_door", "Secret Prismarine Bricks Door", () -> new DoorBlock(Block.Properties.copy(Blocks.PRISMARINE_BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<DoorBlock> SECRET_DARK_PRISMARINE_DOOR = registerDoorBlock("secret_dark_prismarine_door", "Secret Dark Prismarine Door", () -> new DoorBlock(Block.Properties.copy(Blocks.DARK_PRISMARINE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));


    //---- TRAPDOORS -------------------------------------------------------------------------------
    public static final RegistryObject<TrapDoorBlock> SECRET_OAK_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_oak_plank_trapdoor", "Secret Oak Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_DARK_OAK_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_dark_oak_plank_trapdoor", "Secret Dark Oak Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_SPRUCE_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_spruce_plank_trapdoor", "Secret Spruce Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_ACACIA_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_acacia_plank_trapdoor", "Secret Acacia Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_BIRCH_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_birch_plank_trapdoor", "Secret Birch Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_JUNGLE_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_jungle_plank_trapdoor", "Secret Jungle Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_CRIMSON_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_crimson_plank_trapdoor", "Secret Crimson Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.CRIMSON_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_WARPED_PLANK_TRAPDOOR = registerTrapdoorBlock("secret_warped_plank_trapdoor", "Secret Warped Plank Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.WARPED_PLANKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<TrapDoorBlock> SECRET_OAK_LOG_TRAPDOOR = registerTrapdoorBlock("secret_oak_log_trapdoor", "Secret Oak Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_DARK_OAK_LOG_TRAPDOOR = registerTrapdoorBlock("secret_dark_oak_log_trapdoor", "Secret Dark Oak Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_SPRUCE_LOG_TRAPDOOR = registerTrapdoorBlock("secret_spruce_log_trapdoor", "Secret Spruce Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_ACACIA_LOG_TRAPDOOR = registerTrapdoorBlock("secret_acacia_log_trapdoor", "Secret Acacia Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_BIRCH_LOG_TRAPDOOR = registerTrapdoorBlock("secret_birch_log_trapdoor", "Secret Birch Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_JUNGLE_LOG_TRAPDOOR = registerTrapdoorBlock("secret_jungle_log_trapdoor", "Secret Jungle Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_CRIMSON_STEM_TRAPDOOR = registerTrapdoorBlock("secret_crimson_stem_trapdoor", "Secret Crimson Stem Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.CRIMSON_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_WARPED_STEM_TRAPDOOR = registerTrapdoorBlock("secret_warped_stem_trapdoor", "Secret Warped Stem Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.WARPED_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_OAK_LOG_TRAPDOOR = registerTrapdoorBlock("secret_stripped_oak_log_trapdoor", "Secret Stripped Oak Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_DARK_OAK_LOG_TRAPDOOR = registerTrapdoorBlock("secret_stripped_dark_oak_log_trapdoor", "Secret Stripped Dark Oak Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.DARK_OAK_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_SPRUCE_LOG_TRAPDOOR = registerTrapdoorBlock("secret_stripped_spruce_log_trapdoor", "Secret Stripped Spruce Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.SPRUCE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_ACACIA_LOG_TRAPDOOR = registerTrapdoorBlock("secret_stripped_acacia_log_trapdoor", "Secret Stripped Acacia Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.ACACIA_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_BIRCH_LOG_TRAPDOOR = registerTrapdoorBlock("secret_stripped_birch_log_trapdoor", "Secret Stripped Birch Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.BIRCH_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_JUNGLE_LOG_TRAPDOOR = registerTrapdoorBlock("secret_stripped_jungle_log_trapdoor", "Secret Stripped Jungle Log Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.JUNGLE_LOG.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_CRIMSON_STEM_TRAPDOOR = registerTrapdoorBlock("secret_stripped_crimson_stem_trapdoor", "Secret Stripped Crimson Stem Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.STRIPPED_CRIMSON_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STRIPPED_WARPED_STEM_TRAPDOOR = registerTrapdoorBlock("secret_stripped_warped_stem_trapdoor", "Secret Stripped Warped Stem Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.WOOD, Blocks.STRIPPED_WARPED_STEM.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<TrapDoorBlock> SECRET_STONE_TRAPDOOR = registerTrapdoorBlock("secret_stone_trapdoor", "Secret Stone Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.STONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_COBBLESTONE_TRAPDOOR = registerTrapdoorBlock("secret_cobblestone_trapdoor", "Secret Cobblestone Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.COBBLESTONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_STONE_BRICKS_TRAPDOOR = registerTrapdoorBlock("secret_stone_bricks_trapdoor", "Secret Stone Bricks Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.STONE_BRICKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_DEEPSLATE_TRAPDOOR = registerTrapdoorBlock("secret_deepslate_trapdoor", "Secret Deepslate Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.DEEPSLATE.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_COBBLED_DEEPSLATE_TRAPDOOR = registerTrapdoorBlock("secret_cobbled_deepslate_trapdoor", "Secret Cobbled Deepslate Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.COBBLED_DEEPSLATE.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_DEEPSLATE_BRICKS_TRAPDOOR = registerTrapdoorBlock("secret_deepslate_bricks_trapdoor", "Secret Deepslate Bricks Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.DEEPSLATE_BRICKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE_BRICKS).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_DEEPSLATE_TILES_TRAPDOOR = registerTrapdoorBlock("secret_deepslate_tiles_trapdoor", "Secret Deepslate Tiles Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.DEEPSLATE_TILES.defaultMaterialColor()).strength(3.0F).sound(SoundType.DEEPSLATE_TILES).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_POLISHED_DEEPSLATE_TRAPDOOR = registerTrapdoorBlock("secret_polished_deepslate_trapdoor", "Secret Polished Deepslate Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_DEEPSLATE.defaultMaterialColor()).strength(3.0F).sound(SoundType.POLISHED_DEEPSLATE).noOcclusion()));

    public static final RegistryObject<TrapDoorBlock> SECRET_BOOKSHELF_TRAPDOOR = registerTrapdoorBlock("secret_bookshelf_trapdoor", "Secret Bookshelf Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.BOOKSHELF.defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()));

    public static final RegistryObject<TrapDoorBlock> SECRET_NETHERRACK_TRAPDOOR = registerTrapdoorBlock("secret_netherrack_trapdoor", "Secret Netherrack Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.NETHERRACK.defaultMaterialColor()).strength(3.0F).sound(SoundType.NETHERRACK).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_NETHER_BRICK_TRAPDOOR = registerTrapdoorBlock("secret_nether_brick_trapdoor", "Secret Nether Brick Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.NETHER_BRICKS.defaultMaterialColor()).strength(3.0F).sound(SoundType.NETHER_BRICKS).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_POLISHED_BLACKSTONE_TRAPDOOR = registerTrapdoorBlock("secret_polished_blackstone_trapdoor", "Secret Polished Blackstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_BLACKSTONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_POLISHED_BASALT_TRAPDOOR = registerTrapdoorBlock("secret_polished_basalt_trapdoor", "Secret Polished Basalt Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_BASALT.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));

    public static final RegistryObject<TrapDoorBlock> SECRET_BLACKSTONE_TRAPDOOR = registerTrapdoorBlock("secret_blackstone_trapdoor", "Secret Blackstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.BLACKSTONE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_ANDESITE_TRAPDOOR = registerTrapdoorBlock("secret_andesite_trapdoor", "Secret Andesite Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.ANDESITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_POLISHED_ANDESITE_TRAPDOOR = registerTrapdoorBlock("secret_polished_andesite_trapdoor", "Secret Polished Andesite Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_ANDESITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_DIORITE_TRAPDOOR = registerTrapdoorBlock("secret_diorite_trapdoor", "Secret Diorite Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.DIORITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_POLISHED_DIORITE_TRAPDOOR = registerTrapdoorBlock("secret_polished_diorite_trapdoor", "Secret Polished Diorite Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_DIORITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_GRANITE_TRAPDOOR = registerTrapdoorBlock("secret_granite_trapdoor", "Secret Granite Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.GRANITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_POLISHED_GRANITE_TRAPDOOR = registerTrapdoorBlock("secret_polished_granite_trapdoor", "Secret Polished Granite Trapdoor", () -> new TrapDoorBlock(Block.Properties.of(Material.STONE, Blocks.POLISHED_GRANITE.defaultMaterialColor()).strength(3.0F).sound(SoundType.STONE).noOcclusion()));

    public static final RegistryObject<TrapDoorBlock> SECRET_QUARTZ_BLOCK_TRAPDOOR = registerTrapdoorBlock("secret_quartz_block_trapdoor", "Secret Quartz Block Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.QUARTZ_BLOCK).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_SMOOTH_QUARTZ_TRAPDOOR = registerTrapdoorBlock("secret_smooth_quartz_trapdoor", "Secret Smooth Quartz Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.SMOOTH_QUARTZ).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_QUARTZ_BRICKS_TRAPDOOR = registerTrapdoorBlock("secret_quartz_bricks_trapdoor", "Secret Quartz Bricks Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.QUARTZ_BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_SANDSTONE_TRAPDOOR = registerTrapdoorBlock("secret_sandstone_trapdoor", "Secret Sandstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_CUT_SANDSTONE_TRAPDOOR = registerTrapdoorBlock("secret_cut_sandstone_trapdoor", "Secret Cut Sandstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.CUT_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_SMOOTH_SANDSTONE_TRAPDOOR = registerTrapdoorBlock("secret_smooth_sandstone_trapdoor", "Secret Smooth Sandstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.SMOOTH_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_RED_SANDSTONE_TRAPDOOR = registerTrapdoorBlock("secret_red_sandstone_trapdoor", "Secret Red Sandstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.RED_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_CUT_RED_SANDSTONE_TRAPDOOR = registerTrapdoorBlock("secret_cut_red_sandstone_trapdoor", "Secret Cut Red Sandstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.CUT_RED_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_SMOOTH_RED_SANDSTONE_TRAPDOOR = registerTrapdoorBlock("secret_smooth_red_sandstone_trapdoor", "Secret Smooth Red Sandstone Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.SMOOTH_RED_SANDSTONE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_BRICKS_TRAPDOOR = registerTrapdoorBlock("secret_bricks_trapdoor", "Secret Bricks Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_PURPUR_TRAPDOOR = registerTrapdoorBlock("secret_purpur_trapdoor", "Secret Purpur Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.PURPUR_BLOCK).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_END_STONE_BRICKS_TRAPDOOR = registerTrapdoorBlock("secret_end_stone_bricks_trapdoor", "Secret End Stone Bricks Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.END_STONE_BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_PRISMARINE_BRICKS_TRAPDOOR = registerTrapdoorBlock("secret_prismarine_bricks_trapdoor", "Secret Prismarine Bricks Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.PRISMARINE_BRICKS).strength(3.0F).sound(SoundType.STONE).noOcclusion()));
    public static final RegistryObject<TrapDoorBlock> SECRET_DARK_PRISMARINE_TRAPDOOR = registerTrapdoorBlock("secret_dark_prismarine_trapdoor", "Secret Dark Prismarine Trapdoor", () -> new TrapDoorBlock(Block.Properties.copy(Blocks.DARK_PRISMARINE).strength(3.0F).sound(SoundType.STONE).noOcclusion()));

}